---
- hosts: all
  sudo: yes
  gather_facts: yes

  tasks:

  - name: install ntp
    apt: name=ntp state=installed update_cache=yes
    when: ansible_os_family == "Debian"

  - name: install ntp
    yum: name=ntp state=installed update_cache=yes
    when: ansible_os_family == "RedHat"

  - name: write our ntp.conf
    copy: src=files/ntp.conf dest=/etc/ntp.conf mode=644 owner=root group=root
    notify: restart ntp

  - name: start ntp
    service: name=ntp state=started
    when: ansible_os_family == "Debian"

  - name: start ntp
    service: name=ntpd state=started enabled=true
    when: ansible_os_family == "RedHat"

  handlers:

  - name: restart ntp
    service: name=ntp state=restarted
    when: ansible_os_family == "Debian"
